name: 'Update output files'
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    container: mtimoustafa/rim-translate
    
    steps:
      - uses: actions/checkout@v4
