name: 'Update output files'
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-output:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'mtimoustafa/RimTranslate'
          path: 'RimTranslate/'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - run: python -m pip install -r RimTranslate/requirements.txt
      - run: python RimTranslate/RimTranslate.py -p "po/" -o "output/"
      - uses: actions/checkout@v4
      - uses: actions4git/add-commit-push@v1
